### ISSUE TITLE
Skipping a deployment with the pypi provider because this repo's name does not match one specified in .travis.yml's deploy.on.repo: phac-nml/bio_hansel

### ISSUE THREAD

**Issue by peterk87** [phac-nml/biohansel#104]
`Skipping a deployment with the pypi provider because this repo's name does not match one specified in .travis.yml's deploy.on.repo: phac-nml/bio_hansel`

https://travis-ci.org/phac-nml/biohansel/builds/560158507#L532

**Potential fix:**

Change this 

https://github.com/phac-nml/biohansel/blob/development/.travis.yml#L21

To: 

```
  on:
    tags: true
    repo: phac-nml/biohansel
    python: 3.6
```
